### ISSUE TITLE
EATL spec bugs from testsuite run

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ExecutionAndTraceLog#232]
- [ ] x-correlator should have a regexp in list-records-of-flow (used as parameter)

- [ ] release-number has in EATL and OAM wrong regexp (missing '\\' before '.')
      This is fixed for EATL openapi.yaml here #231 and for OAMLog here openBackhaul/OamLog#224

**Comment by IswaryaaS** [comment]
Detailed issue for issue#2 could be found here https://github.com/openBackhaul/ExecutionAndTraceLog/issues/218

**Comment by PrathibaJee** [comment]
We have two problems indicated in this issue.
Problem#1 is to include a pattern for the list-record-of-flows. 
As per the explanation in https://github.com/openBackhaul/RequestSequenceRepresentation/issues/4#issue-1790853130 , there is no change required in the OAS.

Since for problem#2 we have a separate issue , closing this issue will be fine.
@IswaryaaS , @DanaSunal  please close this issue if it is fine.

**Comment by IswaryaaS** [comment]
@PrathibaJee , thanks for letting us know about how problem#1 has been handled. 
Closing the issue as problem#2 shall be handled in https://github.com/openBackhaul/ExecutionAndTraceLog/issues/218
