### ISSUE TITLE
Proposal to include additional attributes in the ExecutionAndTraceLog records.

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ExecutionAndTraceLog#255]
Currently , we are recording the following details into the EATL application.
1. x-correlator
2. trace-indicator
3. user
4. originator
5. application-name
6. release-number
7. operation-name
8. response-code
9. timestamp
10. stringified-body
11. stringified-response

proposing to include the following information as well , as it will help in investigation in case of any failures.
1. url :   Currently , we are recording the operation-name. Shall we also record the url ? In case of a 404 response code for a request , we can find out whether problem is because of
            -       Improper tcp-client configuration 
            -       Application is down

2. exec-time :  For every service , exec-time will be present in the response header. shall we also log this information ? By recording this , in case of a performance degrade , we shall able to find out which service contributes to an overall delay.

Requesting to consider this proposal for future enhancement.
If this proposal is accepted , separate issue shall be created in OAMLog as well.

**Comment by openBackhaul** [comment]
The requestBody of the /v1/record-service-request shall be complemented by the following two attributes:

- URL field only to be added in case the consuming application is sending the record, because it could not reach the serving application.  
The URL attribute shall not be required (also for backward compatibility reasons).

- The exec-time only to be added in case the serving application is sending the record.  
The exec-time attribute shall not be required (also for backward compatibility reasons).

Scheduling shall be checked, as the ApplicationPattern needs to be complemented, too.

**Comment by openBackhaul** [comment]
Changed as proposed.
