### ISSUE TITLE
/v/1Bequeath-your-data-and-die Trace indicator Subscription forwardings are not getting incremented as expected

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/ExecutionAndTraceLog#262]
As a part of bequeath-your-data-and-die , to transfer the data from old-release to new-release , we are utilizing the following forwardings , for which all the OUTPUTS shall be triggered from the old-release to new-release.

PromptForBequeathingDataCausesTransferOfListOfApplications
PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease
PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease
PromptForBequeathingDataCausesRObeingRequestedToStopNotificationsToOldRelease
promptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement
promptForBequeathingDataCausesRequestForDeregisteringOfOldRelease

Each request should be considered as a parallel request and not serialized.
For example , for 
promptForBequeathingDataCausesRequestForDeregisteringOfOldRelease
All the applications subscribed for deregistration notification shall be transferred from old-release to new-release.

- Expectation
“Bequeath-your-data-and-die” [1]
promptForBequeathingDataCausesRequestForDeregisteringOfOldRelease
“notify-deregistration”[1.x]
“notify-deregistration”[1.x+1]
..
..
“notify-deregistration”[1.x+(n-1)]

> Priority:High

**Comment by DanaSunal** [comment]
I have created a prototype, do these requests have the expected trace indicator format? (All of them are executed when calling bequeathYourDataAndDie on EATL).

**Request from prompt PromptForBequeathingDataCausesTransferOfListOfApplications**
Request sent RegistryOffice, with trace-indicator 1.1 
Request sent TypeApprovalRegister, with trace-indicator 1.2 
Request sent ExecutionAndTraceLog, with trace-indicator 1.3 
Request sent OamLog, with trace-indicator 1.4 
Request sent AdministratorAdministration, with trace-indicator 1.5 
Request sent ApplicationLayerTopology, with trace-indicator 1.6 
Request sent OperationKeyManagement, with trace-indicator 1.7 
Request sent CurrentController, with trace-indicator 1.8 

**Request from prompt PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease**
Request sent {"subscriber-application":"ExecutionAndTraceLog","subscriber-release-number":"2.0.2","subscriber-operation":"/v1/regard-application","subscriber-protocol":"HTTP","subscriber-address":{"ip-address":{"ipv-4-address":"127.0.0.1"}},"subscriber-port":3003}, with trace-indicator 1.1 

**Request from prompt PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease**
Request sent {"subscriber-application":"ExecutionAndTraceLog","subscriber-release-number":"2.0.2","subscriber-operation":"/v1/disregard-application","subscriber-protocol":"HTTP","subscriber-address":{"ip-address":{"ipv-4-address":"127.0.0.1"}},"subscriber-port":3003}, with trace-indicator 1.1 

**Request from prompt PromptForBequeathingDataCausesRObeingRequestedToStopNotificationsToOldRelease**
Request sent {"subscription":"/v1/notify-approvals","subscriber-application":"ExecutionAndTraceLog","subscriber-release-number":"2.0.1"}, with trace-indicator 1.1 
Request sent {"subscription":"/v1/notify-withdrawn-approvals","subscriber-application":"ExecutionAndTraceLog","subscriber-release-number":"2.0.1"}, with trace-indicator 1.2 

**Request from prompt PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement**
Request sent {"current-application-name":"ExecutionAndTraceLog","current-release-number":"2.0.1","future-application-name":"ExecutionAndTraceLog","future-release-number":"2.0.2","future-protocol":"HTTP","future-address":{"ip-address":{"ipv-4-address":"127.0.0.1"}},"future-port":3003}, with trace-indicator 1.1 

**Request from prompt PromptForBequeathingDataCausesRequestForDeregisteringOfOldRelease**
Request sent ExecutionAndTraceLog, with trace-indicator 1.1

**Comment by DanaSunal** [comment]
Please review the comment above @PrathibaJee

**Comment by PrathibaJee** [comment]
On receiving a bequeath-your-data-and-die request, application will do the following , 
- Update the "NewRelease" application information in the LogicalTerminationPoint(LTP)
- Forward the LTP(s) updation to ApplicationLayerTopology(ALT)
- Start the softwareUpgrade process

Lets consider the following example , 

1. bequeath-your-data-and-die request hits the application with trace-indicator 1
2. Lets say , if there is a updation required in the tcp server , http server of the "NewRelease" then /v1/update-ltp will be triggered to ALT
/v1/update-ltp 1.1
/v1/update-ltp 1.2
> From the "forwardingAutomationInputList" , we shall know that there are two parallel requests we triggered.
> So, the starting incrementer for the software upgrade will be "3" , that is 1.3
> Further in the software upgrade , we have the following forwarding , 
4. PromptForBequeathingDataCausesTransferOfListOfApplications
if we have 10 applications , (since all of them have to be initiated in parallel)
to all the 10 application , 
/v1/regard-application 1.3
/v1/regard-application 1.4
..
..
..
/v1/regard-application 1.12

5. PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease 
to RegistryOffice(RO)
/v1/notify-approvals 1.13

6. PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease
to RO 
/v1/notify-withdrawn-approvals 1.14

7. PromptForBequeathingDataCausesRObeingRequestedToStopNotificationsToOldRelease
to RO 
/v1/end-subscription 1.15

8. promptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement
to RO 
/v1/relay-server-replacement 1.16

9. promptForBequeathingDataCausesRequestForDeregisteringOfOldRelease
to RO 
/v1/deregister-application 1.17
