### ISSUE TITLE
OAS : callback uri definition : /v1/regard-application

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#37]
Problem:

Operation-name is statically defined in callback request "ApprovedApplicationCausesRequestForServiceRequestInformation"

Proposal:

Line 1056 to be changed from "https://{$request.body#application-address}:{$request.body#application-port}/v1/redirect-service-request-information" to "https://{$request.body#application-address}:{$request.body#application-port}[/core-model-1-4:control-construct/logical-termination-point=eatl-0-0-1-op-s-0002/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]"

Related issue : https://github.com/openBackhaul/OamLog/issues/6

**Comment by openBackhaul** [comment]
There is a couple of aspects to be clarified:
- All URIs containing references into the RequestBody (e.g. _{$request.body#application-port}_) have been corrected in such a way that references are pointing into the internal data structure instead. Reason: Data sent in the RequestBody has to update the internal data structure first and the consequent requests (callbacks) have to be sent afterwards. The updated URI can be found in line 926 of the EaTL OAS.
- The proposed solution is using an OperationServer uuid in a path, which is ending at an OperationClient attribute. This is definitively incorrect.
- The _/v1/redirect-service-request-information_ OperationClient has 8 occurrences (e.g. _eatl-2-0-0-op-c-im-ro-2-0-0-004_ or _eatl-2-0-0-op-c-im-tar-1-0-0-000_).
- A generic representation of the UUID would look like _eatl-2-0-0-op-c-im-*-*-*-*-*_, which I found not very meaningful. This is why I decided to put the concrete operation name, which will potentially outdate.

@IswaryaaS : If you would agree, please close the issue. Otherwise, please guide the discussion by additional reason, question or doubt.

**Comment by IswaryaaS** [comment]
Thanks for clarification. Regarding the clarifications, please find my comments below:
Point 1: The new logic looks fine that it will create instances in config file and with that instances, callbacks will be further processed. 
Point 2: Sorry, In the proposal given, the uuid must have been an operation-client instance like eatl-1-0-0-op-c-2**0 which is meant to be pointing to operation-client-instance of /v1/redirect-service-request-information
Point 3: I agree with the point, that since we have different sequence number and it would not be meaningful if we use this pattern to  refer /v1/redirect-service-request-information.

I have the following proposal for substituting the concrete operation-name with path reference:
_Can we update the sequence number for /v1/redirect-service-request-information operation-clients of all applications to 004 (similar to RO)
Then, the uuid(s) of operation-client//v1/redirect-service-request-information of TAR, EATL and other applications will become eatl-2-0-0-op-c-im-tar-2-0-0-004, eatl-2-0-0-op-c-im-eatl-2-0-0-004 etc.., with common sequence number 004. so that we can define a pattern like eatl-2-0-0-op-c-im-\*-\*-\*-\*-004. Please let me know your thoughts._

**Comment by IswaryaaS** [comment]
Thanks for updating the uuid pattern
